### ISSUE TITLE
GUI text issue

### ISSUE THREAD

**Issue by oldman20** [DeedleFake/trayscale#105]
I installed via flatpak, cant see anything, even change themes
![Screenshot from 2024-04-04 11-26-37](https://github.com/DeedleFake/trayscale/assets/39668756/13915285-c211-4b5b-90cc-6ebbc899d40b)

Im running Arcolinux 24.4.03 version

**Comment by DeedleFake** [comment]
Ooh, that's a new one. Huh. Any error messages when you run it in the console via, for example, `flatpak run dev.deedles.Trayscale`?

**Comment by oldman20** [comment]
> Ooh, that's a new one. Huh. Any error messages when you run it in the console via, for example, `flatpak run dev.deedles.Trayscale`?

$ flatpak run dev.deedles.Trayscale
2024/04/04 12:17:07 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
all here output, dear!

**Comment by DeedleFake** [comment]
Do you have any issues with other Gtk4 or Libadwaita apps via Flatpak? If you don't have any you can test easily, try installing the Adwaita demo from the GNOME Nightly repo.

**Comment by oldman20** [comment]
> Do you have any issues with other Gtk4 or Libadwaita apps via Flatpak? If you don't have any you can test easily, try installing the Adwaita demo from the GNOME Nightly repo.
hơw to test on arch?

**Comment by oldman20** [comment]
![Screenshot from 2024-04-04 12-52-17](https://github.com/DeedleFake/trayscale/assets/39668756/380d6428-7289-4b88-8739-d0eab1b87cd4)
![Screenshot from 2024-04-04 12-52-32](https://github.com/DeedleFake/trayscale/assets/39668756/2ab2b2b2-5525-4d44-a954-020420646cf7)
seem not fines

**Comment by DeedleFake** [comment]
That is a Gtk3 app by the looks of it, not Gtk4 and definitely not Libadwaita.

**Comment by DeedleFake** [comment]
Try installing the Adwaita Demo app from the GNOME Nightly repo: https://wiki.gnome.org/Apps/Nightly

**Comment by oldman20** [comment]
> Try installing the Adwaita Demo app from [the GNOME Nightly repo](https://wiki.gnome.org/Apps/Nightly).

humh, seem i have issue with gtk4
`$ flatpak run org.gnome.Epiphany.Devel//master

(epiphany:2): Gsk-WARNING **: 10:27:14.156: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:14.156: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Toplevel': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"



(epiphany:2): epiphany-WARNING **: 10:27:14.517: Failed to search secret storage (is the secret service or secrets portal broken?): org.freedesktop.DBus.Error.ServiceUnknown

(epiphany:2): Gsk-WARNING **: 10:27:19.110: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:19.110: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Popup': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"



(epiphany:2): Gsk-WARNING **: 10:27:20.177: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:20.178: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Popup': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"



(epiphany:2): Gsk-WARNING **: 10:27:24.282: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:24.282: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Popup': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"



(epiphany:2): Gtk-WARNING **: 10:27:26.742: Error embedding AT-SPI socket: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

(epiphany:2): Gsk-WARNING **: 10:27:29.278: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:29.278: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11DragSurface': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"



(epiphany:2): Gsk-WARNING **: 10:27:32.540: Linking failure in shader:
Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"

Gsk-Message: 10:27:32.541: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkX11Popup': Linking failure in shader: Fragment info
-------------
0(305) : error C1115: unable to find compatible overloaded function "texture(struct __samplerExternal, vec2)"
`

**Comment by DeedleFake** [comment]
Since this is not a Trayscale bug, I'm going to go ahead and close this.

The problem you're having looks like it's probably related to NixOS/nixpkgs#244459. You said that you're on Arcolinux, which I know is Arch-based, but are you using the Nix package manager?
