### ISSUE TITLE
meta: Flatpak support

### ISSUE THREAD

**Issue by DeedleFake** [DeedleFake/trayscale#11]
I'm not sure how technically feasible this is, due to the low-level stuff that Tailscale needs access to, but if possible it would be great to get this packaged up with Flatpak. In particular, that might make it possible to run on the Steam Deck nice and easily, which would be nice, at least until the [official support](https://tailscale.com/blog/steam-deck/) is added.

Questions:

* Is it feasible to interact with the Tailscale daemon and CLI from inside of a Flatpak environment?
* Is it possible to package the Tailscale daemon and CLI inside of the Flatpak, thus eliminating non-Flatpak dependencies?

**Comment by bi0shacker001** [comment]
I'm not the dev, but I can speak from system-level knowledge
Integrating the tailscale daemon into a flatpak would be extremely challenging (flatpaks run in the user's context, and the tailscale daemon MUST run with kernel-level permissions, as it's a networking daemon.), but even if it could be done, that would then be putting all the work of updating the flatpak both for application updates, and for tailscale daemon updates.

Nothing against Flatpaks, I love them, but they're not good for system-level tools. Not the right use-case.

Packaging the flatpak with just the application is doable if flatpak allows you to execute binaries that exist outside the flatpak. If not, since this application pretty much does just that (it calls the tailscale binary), that wouldn't work either.

**Comment by DeedleFake** [comment]
Thanks for info. It seems to match what I found from a brief foray into the process of building a Flatpak. It may depend on how many external dependencies Tailscale itself has. It _is_ written in Go, but I would guess that there's some cgo usage somewhere in its dependencies. If not, bundling it might actually be feasible, though the permissions on the resulting Flatpak will be pretty loose.

About maintaining the package, I _am_ the dev and maintainer of this project. My original purpose with this project was to try to improve the Tailscale situation on Steam Deck, and my plan was to make a nice UI so that I could package it into a Flatpak and install it without having to worry about FS immutability, so having to update the Flatpak is something I was already anticipating. I didn't know at the time, and still don't for sure, what the feasibility of that is, but I wanted a Linux UI either way. Even if packaging with the `tailscaled` and `tailscale` binaries doesn't work, I'm pretty sure that packaging just the UI should work. I should probably update the UI to show a nice error page if `tailscale` isn't in your `$PATH`.

**Comment by DeedleFake** [comment]
Crazy alternative that just occurred to me and I kind of want to look into: `tailscaled` is itself fully open-source and written in Go. It _might_ be possible to run it entirely embedded into Trayscale as if it were a library. This should obviously _not_ be the default, but, if it works, it could be enabled during the build via a build tag and then activated with a command-line flag. The Flatpak would then be built with that tag and add the flag automatically, or at least have some easy way to add the flag.

**Comment by DeedleFake** [comment]
I've started working on a Flatpak manifest in the `flatpak` branch. It seems that Flatpaks _can_ execute external commands. Inside of the sandbox, there's a special `flatpak-spawn` command that can execute commands from the host system. Still not as nice as bundling `tailscale` into the Flatpak. I'll try that next.

**Comment by DeedleFake** [comment]
I successfully created a Flatpak manifest that seems to work and have submitted a pull request to add it to Flathub: flathub/flathub#3958

The current implementation assumes `tailscaled` to be running already and configured as explained in the README and that `tailscale` is accessible in your `$PATH`.

**Comment by DeedleFake** [comment]
Trayscale is now available on Flathub: https://flathub.com/apps/details/dev.deedles.Trayscale
