### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Rattlyy** [DeedleFake/trayscale#128]
please add dark mode 🙏🏼

**Comment by DeedleFake** [comment]
It already has dark mode as it uses Libadwaita. What desktop environment are you using?

**Comment by Rattlyy** [comment]
Hyprland

Il giorno mar 2 lug 2024 alle 22:51 DeedleFake ***@***.***>
ha scritto:

**Comment by DeedleFake** [comment]
Try running the following command:

```
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
```

**Comment by vahtos** [comment]
I am using the flatpak and have the same issue. I tried the command

```
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
```

It had no effect. I even restarted the computer and retried.

**Comment by DeedleFake** [comment]
Trayscale uses Libadwaita and is unaffected by theming. The only things that affect its appearance are fonts and dark mode.

I believe that that command will only activate dark mode while in GNOME. If you are in KDE, it should respect the KDE dark mode setting. That's how it works on my computer.
