### ISSUE TITLE
Filling .xsession-errors

### ISSUE THREAD

**Issue by cinderblockgames** [DeedleFake/trayscale#135]
I'm getting this error in ~/.xsession-errors every five seconds:

    ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"

I am not currently connected to my tailnet.  These logs apparently filled up my 2tb drive.

**Comment by DeedleFake** [comment]
Yeah, Trayscale produces quite a bit of log output. It should normally not really go anywhere at all, though, I would expect. What's your X11 setup? Are you using a display manager (GDM, SDDM, etc.), or are you running X manually using `startx` or `xinit` or something? How are you starting Trayscale?

**Comment by cinderblockgames** [comment]
I put it into Startup Applications with this command:

    /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=trayscale dev.deedles.Trayscale --hide-window

I'm on Linux Mint Debian Edition.  No idea what my X11 setup is - whatever the default is for LMDE.  Not doing anything manual with it.

**Comment by DeedleFake** [comment]
It seems this is a moderately common problem with Linux Mint, judging from a quick Google search. One suggestion I saw is something that I was going to suggest anyways, namely changing your above startup line to

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=trayscale dev.deedles.Trayscale --hide-window &> /dev/null
```

That'll cause everything it logs to just get discarded.

**Comment by cinderblockgames** [comment]
Perfect; thank you!  I will do that.
