### ISSUE TITLE
Connect/Disconnect not functioning

### ISSUE THREAD

**Issue by AngiesBloke** [DeedleFake/trayscale#136]
Ubuntu desktop 22.04. Blue Connect/Disconnect button not functioning. Command line up/down commands all OK and button reflects current status

**Comment by DeedleFake** [comment]
If you run Trayscale in a terminal, is there an output when trying to connect/disconnect?

**Comment by AngiesBloke** [comment]
Issue resolved. I started to get a few other erratic problems with Trayscale so I removed it and reinstalled after reboot. All is now fine with both Tailscale and Trayscale, using the GUI or CLI. Many thanks.
