### ISSUE TITLE
Ability to run as root?

### ISSUE THREAD

**Issue by MichaelFisher1997** [DeedleFake/trayscale#145]
Feel free to correct me if I misunderstand any of this. (and sorry for the dyslexia)

So the company I work at is fully remote, we have recently swapped to Linux laptops and it was my task to plan and set them up.
For what we do and need, Debian 12 seems the best fit. To be able to remotely manage the laptops to help with any issues that might appear, I set up a tailscale network on all laptops, with a SSH key in the root user, and have it locked down to only connections through tailscale and with the specific key we use.
I also got ansible keeping on top of updates....... you get it, basically made it super easy to maintain the devices and help people who might not be familiar with Linux, been about 8 months now with very few issues but here is my problem.

Guy I work with needed to change our VPN hat we only need to be connected to for specific clients who white list IPs that can connect to things like their database, our old wire guard VPN broke and was kinda just in a mess from before either of us come into this job, so I mentioned we can use tailscale like a traditional VPN without all the config faff you normally get.
so I had a week off and was told that he set up trayscale on people's linux laptops (also tried another similar project) and when I got back, I could not log in to any laptops in ssh, and it just completely messed with the connections, I assume its because they where set up using root and then running "sudo tailscale set --operator=$USER" probably messed the whole config up.
--reset brought it back to normal.

So, while I personally am happy using the terminal, we are moving more people over to Linux atm, and some of them might not be too comfortable using a terminal if this could be run like a lot of other GUI apps like KDE's discovery store, they have a pop up asking for password, It would just make the whole process of connecting to an exit node and disconnecting much simpler .

I have a bit of go experience so I could try and help, but I have very little experience with making GUI apps.
But it would save me having to try and make my own even if it's just that one button to connect and disconnect from an exit node

**Comment by DeedleFake** [comment]
Let me see if I've got this. You are asking for two things:

1. The ability to run Trayscale as root? I'm not sure why you'd need to. If you have set Tailscale's operator then, as far as I am aware, it should function identically to otherwise except that that user can control the Tailscale daemon via the `tailscale` command. But even if it didn't work, you should already be able to run Trayscale as root and it _should_ just work, I would think. I've never tried it myself, though.
2. #67.

**Comment by MichaelFisher1997** [comment]
Sorry for taking a while to get back.
I've had a lot of issues when running Tailscale with the operator set, which is why Ive been wanting a method to run root.
I've tried running it as Root (flatpack version on Debian 12) but it does not work, buttons and switches don't activate.
Really all I need is for people to have the option to route traffic through an exit node, and then default back to normal when finished, the issue I have is people now are turning tailscale fully off....

Given we have recently renewed everyone's devices, I've tried to replicate my issues, thinking maybe it's a bug on the tailscales side of things.
However, we have not been able to recreate the issues and have got user operators to work on them.
So you can close this issue as I don't want to waste any more of your time, I don't need to run it as root anymore

**Comment by DeedleFake** [comment]
Alright. Strange that it wasn't working before, but glad it is now.
