### ISSUE TITLE
Cursor supersizes when hovering window

### ISSUE THREAD

**Issue by hypergonial** [DeedleFake/trayscale#164]
When Trayscale runs under Wayland, the cursor seems to grow *quite a bit* in size, with this being spammed in the logs while the cursor is being moved over the window:

```
WARN ../gtk/gdk/wayland/gdkcursor-wayland.c:210 cursor image size (64) not an integer multiple of theme size (24) priority=4 code_file=../gtk/gdk/wayland/gdkcursor-wayland.c code_line=210 code_func=_gdk_wayland_cursor_get_buffer glib_domain=Gdk
```

I installed via the `trayscale` AUR package.

System Info:
```
OS: Arch Linux x86_64 
Host: 16Z90P-G.AA78H 0.1 
Kernel: 6.10.10-zen1-1-zen 
DE: Plasma 6.1.5 (Wayland)
WM: kwin 
Theme: Colloid-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 15680MiB 
```

| Outside Window  | Inside Window |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/db10378d-3dbd-4eb5-97e0-364df2ba808c)  | ![image](https://github.com/user-attachments/assets/990b86dd-ff49-4119-956b-edea9598cdf0)  |

**Comment by DeedleFake** [comment]
This is not a Trayscale bug. It is happening in Gtk4. Please report it there.
