### ISSUE TITLE
crashes with trayscale 0.14

### ISSUE THREAD

**Issue by hetzbh** [DeedleFake/trayscale#171]
I'm using Ubuntu 24.04.1 LTS with the default desktop, app is installed using the Flatpak

As soon as I launch trayscale, it shows the window that it's not connected, and after 4-5 seconds it crashes with this (long) error message..

[errorlog.txt](https://github.com/user-attachments/files/17756430/errorlog.txt)

However, when I click to connect within these 4-5 seconds, the app doesn't crash...

Any suggestion? also, where the trayscale binary is located? I can't find it on the path...

**Comment by DeedleFake** [comment]
Flatpak installs applications in a sandbox. It should have added it to the path as `dev.deedles.Trayscale`, though, which is pretty much just a wrapper around `flatpak run dev.deedles.Trayscale`.

The crash, on the other hand, seems to be the same as #160. I've been working on that one recently, but it seems to be something that's only happening with _some_ Flatpak installations. I use the Flatpak version on two of my own machines and neither has this problem.
