### ISSUE TITLE
[Feature request] Headscale support

### ISSUE THREAD

**Issue by Twig6943** [DeedleFake/trayscale#172]
Not sure if this is a thing. (Doesn't seem to be)

**Comment by DeedleFake** [comment]
Good news: It is already a thing.
![image](https://github.com/user-attachments/assets/7f56195b-a656-4479-bbb7-91055806f52f)

**Comment by Twig6943** [comment]
Maybe mention this over at flathub so people don't end up making similiar issues to this?

![Screenshot_20241202-083541_Cromite](https://github.com/user-attachments/assets/a8893bd5-8c39-4141-a72c-c9b692eebeac)
