### ISSUE TITLE
posible errors?

### ISSUE THREAD

**Issue by konn-neko** [DeedleFake/trayscale#24]
`ubuntu@Ubuntu-laptop:~$ go install deedles.dev/trayscale/cmd/trayscale@latest`
`# github.com/diamondburned/gotk4/pkg/glib/v2`
`go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220914035633-4e35b1a80848/glib/v2/gfileutils.go:745:12: could not determine kind of name for C.GFileSetContentsFlags`
`go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.0.0-20220914035633-4e35b1a80848/glib/v2/gfileutils.go:758:2: could not determine kind of name for C.g_file_set_contents_full
`

i get these when trying to install

**Comment by DeedleFake** [comment]
That's probably caused by an incompatible version of the C libraries. What version of GLib do you have installed?

**Comment by konn-neko** [comment]
> That's probably caused by an incompatible version of the C libraries. What version of GLib do you have installed?

im not sure, how do i check?

**Comment by konn-neko** [comment]
gir1.2-dbusmenu-glib-0.4:amd64			install
gir1.2-glib-2.0:amd64				install
gir1.2-packagekitglib-1.0			install
gir1.2-upowerglib-1.0:amd64			install
glib-networking:amd64				install
glib-networking:i386				install
glib-networking-common				install
glib-networking-services			install
libavahi-glib1:amd64				install
libdbus-glib-1-2:amd64				install
libdbusmenu-glib4:amd64				install
libgeocode-glib0:amd64				install
libglib-object-introspection-perl		install
libglib-perl:amd64				install
libglib2.0-0:amd64				install
libglib2.0-0:i386				install
libglib2.0-bin					install
libglib2.0-data					install
libglib2.0-dev:amd64				install
libglib2.0-dev-bin				install
libglibmm-2.4-1v5:amd64				install
libjson-glib-1.0-0:amd64			install
libjson-glib-1.0-common				install
libmbim-glib4:amd64				install
libmm-glib0:amd64				install
libpackagekit-glib2-18:amd64			install
libpoppler-glib8:amd64				install
libpulse-mainloop-glib0:amd64			install
libqmi-glib5:amd64				install
libsnapd-glib1:amd64				install
libupower-glib3:amd64				install
ruby-glib2:amd64				install

**Comment by DeedleFake** [comment]
What's the output of `apt show libglib2.0-0`? Also, do you have the `libglib2.0-dev` package installed?

**Comment by konn-neko** [comment]
> apt show libglib2.0-0
```
Package: libglib2.0-0
Version: 2.72.1-1
Priority: important
Section: libs
Source: glib2.0
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4,174 kB
Depends: libc6 (>= 2.34), libffi8 (>= 3.4), libmount1 (>= 2.35.2-7~), libpcre3, libselinux1 (>= 3.1~), zlib1g (>= 1:1.2.2)
Recommends: libglib2.0-data, shared-mime-info, xdg-user-dirs
Breaks: gimp (<< 2.10.14-3~), glib-networking-tests (<< 2.70.0~), gnome-keyring (<< 40.0-3~), libgirepository-1.0-1 (<< 1.62.0-4~), libgladeui-2-6 (<< 3.22.2), libsoup2.4-tests (<< 2.72.0-3~)
Homepage: https://wiki.gnome.org/Projects/GLib
Task: minimal, server-minimal
Download-Size: 1,460 kB
APT-Manual-Installed: no
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
Description: GLib library of C routines
 GLib is a library containing many useful C routines for things such
 as trees, hashes, lists, and strings.  It is a useful general-purpose
 C library used by projects such as GTK+, GIMP, and GNOME.
 .
 This package contains the shared libraries.
```
and i do have libglib2.0-dev installed

**Comment by konn-neko** [comment]
theres a chance it was because of my ubuntu version

**Comment by konn-neko** [comment]
so many things my laptop doesnt have installed, apparently

like
libadwaita-1.pc

**Comment by DeedleFake** [comment]
Is this still an issue?
