### ISSUE TITLE
Support multiple Tailscale accounts

### ISSUE THREAD

**Issue by devmattrick** [DeedleFake/trayscale#61]
Tailscale clients [now supports multiple accounts](https://tailscale.com/blog/fast-user-switching/). It'd be neat to have the option to switch between multiple Tailscale accounts in Trayscale as well to match the official apps.

**Comment by DeedleFake** [comment]
Trayscale itself does not handle authentication, but I did add support recently for reauthenticating for key renewal when necessary. It may be possible for me to add a menu option that lets you reauthenticate with a new account. I'll see what I can do.

**Comment by devmattrick** [comment]
I don't think it necessarily needs to handle authentication, it just needs to run `tailscale switch --list` to get a list of authenticated accounts and `tailscale switch <account name>` to switch between them.
