### ISSUE TITLE
In KDE Plasma click on tray icon shows [Show] and [Quit]

### ISSUE THREAD

**Issue by marcellmars** [DeedleFake/trayscale#73]
I think it would be great if a single click could open the app.

Most of the time, I want it to [Show], and only occasionally do I want to click [Quit] in a dropdown from the tray icon. Even when I want to exit the app, I often want to check the configurations, maybe disconnect before hitting [Quit], etc.

I'm not sure if this behavior is exclusive to KDE Plasma.

Thank you for your work.

**Comment by DeedleFake** [comment]
That would be nice, but unfortunately the [`systray`](https://pkg.go.dev/fyne.io/systray) package has no support for clicking on the icon and it's not a very high priority. If the package gets support for it, I'll add it, but until then it's not planned. Sorry.
