### ISSUE TITLE
add support for headscale through --login-server param in tailscale up

### ISSUE THREAD

**Issue by aderumier** [DeedleFake/trayscale#75]
Hi,
headscale is an opensource implementation of headscale server.

https://github.com/juanfont/headscale

It's compatible with the official tailscale client, it just need to be called with

```
tailscale up --login-server https://headscale.server.fqdn
```

It could be great to be able to use this option in trayscale.

For authentification with oidc, I'm not sure how it's working with official tailscale server, but 
tailscale up is displaying this mesage:

~/tailscale up --login-server https://....
```
To authenticate, visit:

https://yourheadscalefqdn443/oidc/register/nodekey:7a170acc018d021ee0b4ded06ed6d8cd8b5583eb7134e55ac09671a48970013e
```
Then I need to authenticate manually through a browser.
(If they are a way to parse this url and auto-open the link, it could be wonderful !)

Then when the browser have authentified,
the "tailscale up" command return "Success."

~/tailscale up --login-server https://....
```
To authenticate, visit:

https://yourheadscalefqdn443/oidc/register/nodekey:7a170acc018d021ee0b4ded06ed6d8cd8b5583eb7134e55ac09671a48970013e
Success.
```
(after the first login, I can simply logout/login without re-authenticate, until the oidc session is valid in headscale)

**Comment by DeedleFake** [comment]
This is currently possible but more complicated than changing other preferences. See https://github.com/tailscale/tailscale/blob/2d3223f557924d408b5d67b80440d6fba264a0fd/ipn/prefs.go#L48-L63.

It is possible that changing it with `EditPrefs()` and restarting the local client manually might work. I'll have to experiment.

**Comment by aderumier** [comment]
Thanks I'll try it this week !
