### ISSUE TITLE
Failure to connect

### ISSUE THREAD

**Issue by etrigan63** [DeedleFake/trayscale#82]
Launching Trayscale (distro or flatpak) gets the following error:

2023/08/20 20:48:08 ERROR get waiting files err="Access denied: file access denied"

The tray icon appears but remaais greyed out despite tailscale being up and running.

**Comment by DeedleFake** [comment]
Have you run `sudo tailscale up --operator=$USER` manually once in the command-line?

**Comment by etrigan63** [comment]
That appears to have solved the problem. Are there any plans to have the app respect dark GTK themes?

**Comment by DeedleFake** [comment]
It uses libadwaita, so it respects GNOME's dark mode setting. See [this thread](https://www.reddit.com/r/gnome/comments/si0phf/how_to_set_new_libadwaita_apps_to_dark_mode/) for a way to change that setting.

**Comment by etrigan63** [comment]
So it only respects the Adwaita theme. Very sad as that is the most horrible theme on the planet. But my main issue is fixed and I will close the ticket.
