### ISSUE TITLE
No tray icon in Fedora 38 GNOME 44

### ISSUE THREAD

**Issue by zilpe** [DeedleFake/trayscale#85]
Great work on the app!

I'm on the latest Fedora 38, which uses GNOME 44, however there is no Trayscale tray icon appearing in the top bar. Not sure why.

**Comment by kedare** [comment]
Same issue with either AppIndicator or this that I prefer : https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
Others apps appear fine (like Armcord for example) but no trayscale.

Unser AlmaLinux 9.2 + Gnome 40.4.0

**Comment by 5olu7ion** [comment]
> Do you have [the AppIndicator extension](https://extensions.gnome.org/extension/615/appindicator-support/) installed?

It's working fine for me with Arch and Gnome 44.5 (Wayland)

**Comment by Jacalz** [comment]
I couldn't get it to show up with Tray Icons Reloaded but installing https://extensions.gnome.org/extension/615/appindicator-support/ worked fine.

**Comment by DeedleFake** [comment]
The `fyne.io/systray` package doesn't support the old X11 tray icon protocol. It only supports the newer D-Bus protocol. Attempting to use a system tray implementation that doesn't support the newer protocol will not work. The [README for Tray Icons: Reloaded](https://github.com/martinpl/tray-icons-reloaded/blob/master/README.md) says

> * It's only works with [Xorg](https://wiki.archlinux.org/index.php/GDM#Use_Xorg_backend) and XWayland.
> * Appindicator and similar extensions are not compatible, disable it (some distributions ship it by default ex. Ubuntu based).

The bottom line is that Trayscale will not work with that extension. Sorry.

**Comment by DeedleFake** [comment]
As the original commenter hasn't responded and there's not enough info here to figure out if this is even a bug or expected behavior for whatever his setup is, I'm going to close this. Feel free to comment if you haven't been able to fix it, @zilpe.
