### ISSUE TITLE
add ability to receive files via UI

### ISSUE THREAD

**Issue by 5olu7ion** [DeedleFake/trayscale#87]
To receive files via tailscale we have to issue the `tailscale file get .` command. This will transfer the file from `/var/lib/tailscale/files/...` to the current folder, and change the ownership of the file(s). It would be nice to issue this command vi UI. The default folder could be `/home/$USER/Downloads` (could also be set via trayscale preferences). 
There is also a lengthy discussion at tailscale: https://github.com/tailscale/tailscale/issues/2312

**Comment by DeedleFake** [comment]
The ability to receive files was added in v0.10.0 (#58).

**Comment by 5olu7ion** [comment]
Great, I somehow missed that from the UI, It works perfectly fine :-) Thanks for your great work!
