### ISSUE TITLE
Using i3 and no tray icon

### ISSUE THREAD

**Issue by abacao** [DeedleFake/trayscale#90]
Hello all,

First, thank for the tool. :tada: 

I'm having issues having the flatpak app in the tray.
Can I do some debugging why isn't the app appearing?

**Comment by FluffBallFloof** [comment]
Can confirm the same issue on my fedora box, here's the relevant lines from the terminal.
![image](https://github.com/DeedleFake/trayscale/assets/39450493/0a37a957-1553-46fe-9e7a-18929a4e93f0)

**Comment by alexfornuto** [comment]
Same issue using Pop! with i3 and polybar with the tray module:

```
2024/01/22 11:41:32 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2024/01/22 11:41:32 systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name is not activatable
```

**Comment by DeedleFake** [comment]
Do you see `org.freedesktop.Notifications` and `org.kde.StatusNotifierWatcher` in the session bus via something like D-Spy?

**Comment by alexfornuto** [comment]
`org.freedesktop.Notifications` is "Activatable" with a PID.

**Comment by cmiles74** [comment]
I'm also using i3, polybar is not displaying the icon in the "tray" module. I don't know if this helps, but waybar (running under Hyperlan) _does_ correctly display the icon.

**Comment by DeedleFake** [comment]
I believe that this is related to polybar/polybar#2010. Trayscale only has support, via `fyne.io/systray`, for the newer D-Bus-based StatusNotifier tray icons. It doesn't support the legacy X11-based tray icon system. It looks like Polybar doesn't support the StatusNotifier icons yet, so this probably just won't work until support for those is added, or maybe `fyne.io/systray` gets support for the legacy icon system.

**Comment by Jacalz** [comment]
I suppose this should be closed due to the same reason as https://github.com/DeedleFake/trayscale/issues/85#issuecomment-2211499721?

**Comment by cbenz** [comment]
Just for people who stumble upon:

I'm under i3 and I can't have the tray icon in the standard i3 status bar, however as mentioned in https://github.com/fyne-io/systray/issues/75#issuecomment-1977843140, after installing `snixembed` it works.
