### ISSUE TITLE
Issue with system Tray on Linux Mint latest version

### ISSUE THREAD

**Issue by Liionboy** [DeedleFake/trayscale#91]
adrian@adrian-huawei-d16:~$ flatpak run dev.deedles.Trayscale
2023/10/18 18:22:26 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2023/10/18 18:22:27 Critical: Adwaita: adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed
2023/10/18 18:22:27 ERROR get waiting files err="Access denied: file access denied"
2023/10/18 18:22:27 ERROR get waiting files err="Access denied: file access denied"
panic: assignment to entry in nil map [recovered]
        panic: closure error: unexpected panic caught: assignment to entry in nil map

Closure added at:
        github.com/diamondburned/gotk4/pkg/glib/v2.IdleAdd at github.com/diamondburned/gotk4/pkg@v0.0.5/glib/v2/coreglib.go:19
        deedles.dev/trayscale/internal/ui.(*App).Run.func1 at deedles.dev/trayscale/internal/ui/app.go:376
        deedles.dev/trayscale/internal/tsutil.(*Poller).Run at deedles.dev/trayscale/internal/tsutil/poller.go:106

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc0003143f0, {0x191e368, 0x1b}, {0xc00001b608, 0x1, 0x1})
        github.com/diamondburned/gotk4/pkg@v0.0.5/core/closure/funcstack.go:104 +0x928
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00001b698?)
        github.com/diamondburned/gotk4/pkg@v0.0.5/core/closure/funcstack.go:122 +0xc5
panic({0x16ab140?, 0x1ad2630?})
        runtime/panic.go:914 +0x21f
deedles.dev/trayscale/internal/ui.(*App).updatePeers(0xc0000b8360, {0xc000000180, 0xc000227d40, {0x0, 0x0, 0x0}})
        deedles.dev/trayscale/internal/ui/app.go:125 +0x1ce
deedles.dev/trayscale/internal/ui.(*App).update(0xc0000b8360, {0xc000000180, 0xc000227d40, {0x0, 0x0, 0x0}})
        deedles.dev/trayscale/internal/ui/app.go:177 +0x165
deedles.dev/trayscale/internal/ui.(*App).Run.func1.1()
        deedles.dev/trayscale/internal/ui/app.go:376 +0x2b
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_sourceFunc(0x1008)
        github.com/diamondburned/gotk4/pkg@v0.0.5/core/glib/glib.go:341 +0xd9
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x3dde210, 0x1, 0x4106c20)
        _cgo_gotypes.go:13957 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xc00011cbc0?, 0x9?, 0x4106c20?)
        github.com/diamondburned/gotk4/pkg@v0.0.5/gio/v2/gapplication_2_28.go:1266 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0002141f8, {0xc0000360a0?, 0x1, 0x1})
        github.com/diamondburned/gotk4/pkg@v0.0.5/gio/v2/gapplication_2_28.go:1266 +0x20b
deedles.dev/trayscale/internal/ui.(*App).Run(0xc0000b8360, {0x1adc370?, 0xc0000b6380?})
        deedles.dev/trayscale/internal/ui/app.go:385 +0x2d0
main.main()
        deedles.dev/trayscale/cmd/trayscale/trayscale.go:25 +0x109

**Comment by DeedleFake** [comment]
This is not an issue with the tray. The crash seems to be happening on this line: https://github.com/DeedleFake/trayscale/blob/master/internal/ui/app.go#L125

Somehow the map is `nil` when the assignment happens. That's odd. I'll look into it.

**Comment by DeedleFake** [comment]
Out of curiosity, is the machine running Trayscale the _only_ node on your tailnet?

**Comment by PlexSheep** [comment]
I'm still facing this issue on LMDE 6.

```zsh
plex@theseus ~ % flatpak run dev.deedles.Trayscale 
2023/11/28 09:43:15 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
```

My machine is not yet registered in my tailnet, I wanted to do that with trayscale, is that a problem? Should I create a new issue for this?

**Comment by edgar-vincent** [comment]
I have the same issue on Linux Mint Cinnamon 21.2 with a machine which is already registered to the tailnet.
