### ISSUE TITLE
500 Internal Server Error: Taildrop disabled; no storage directory

### ISSUE THREAD

**Issue by PlexSheep** [DeedleFake/trayscale#97]
When starting trayscale with `flatpak run dev.deedles.Trayscale`, I get the following error spammed into the console endlessly. Using the app does not work too, the window opens but the connect button does nothing. I can open the settings and set some things but it seems they are resetting.

```zsh
plex@theseus ~ % flatpak run dev.deedles.Trayscale 
2023/11/28 20:29:49 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2023/11/28 20:29:49 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
2023/11/28 20:29:49 Critical: Adwaita: adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed
2023/11/28 20:29:49 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
2023/11/28 20:29:49 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
2023/11/28 20:29:49 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
2023/11/28 20:29:49 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
...
```
 (This message spams until I stop executing)

I haven't ever done anything with taildrop, even had to look up what it is. There was no connection to my controlserver as of yet, so this is purely client side. I recently switched from Fedora 39 with Plasma to LMDE 6, but there should be no configurations left for trayscale.

**System Information**
```zsh
plex@theseus ~ % inxi       
CPU: 12-core (4-mt/8-st) 12th Gen Intel Core i5-1240P (-MST AMCP-)
speed/min/max: 445/400/4400:3300 MHz Kernel: 6.1.0-13-amd64 x86_64 Up: 6h 19m
Mem: 5409.7/64012.4 MiB (8.5%) Storage: 931.51 GiB (25.1% used) Procs: 373
Shell: Zsh inxi: 3.3.26

plex@theseus ~ % cat /etc/os-release   
PRETTY_NAME="LMDE 6 (faye)"
NAME="LMDE"
VERSION_ID="6"
VERSION="6 (faye)"
VERSION_CODENAME=faye
ID=linuxmint
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
ID_LIKE=debian
DEBIAN_CODENAME=bookworm
```

**Comment by DeedleFake** [comment]
Do you have the Tailscale daemon installed and running? Unfortunately, it can't be run inside the Flatpak sandbox, so it needs to be installed and run separately. You also need to set the user that Trayscale is run as as the Tailscale operator user. See the Trayscale README for more info.

**Comment by PlexSheep** [comment]
After having set tailscale up with the CLI, the app is now working (it generates a new host, not using the one which I created with the CLI). The taildrop error is also gone from the stdout.

**Comment by PlexSheep** [comment]
Update: The taildrop error is still present, even with a working tailscale setup, but not spamming like before.
```zsh
plex@theseus ~ % flatpak run dev.deedles.Trayscale 
2023/11/29 08:58:06 systray error: failed to request name: org.freedesktop.DBus.Error.ServiceUnknown
2023/11/29 08:58:07 Critical: Adwaita: adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed
2023/11/29 09:00:06 Critical: Adwaita: adw_application_window_set_content: assertion 'gtk_widget_get_parent (content) == NULL' failed
2023/11/29 09:00:09 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
2023/11/29 09:00:14 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
```

**Comment by DeedleFake** [comment]
Taildrop needs to be enabled for your account in order to work. The error message when it isn't is an annoyance, for sure, but shouldn't be a problem. I'll see what I can do to reduce the spam when I get a chance.

**Comment by amwalters** [comment]
I'm also getting spammed. I don't use taildrop, any way to disable this check?

Version:
tailscale: 1.74.1-1 (from archlinux extra repo)
trayscale: 0.13.4-1 (from AUR)

`Sep 21 14:37:46 AMWt590 trayscale[4828]: 2024/09/21 14:37:46 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:37:51 AMWt590 trayscale[4828]: 2024/09/21 14:37:51 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:37:56 AMWt590 trayscale[4828]: 2024/09/21 14:37:56 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:01 AMWt590 trayscale[4828]: 2024/09/21 14:38:01 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:06 AMWt590 trayscale[4828]: 2024/09/21 14:38:06 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:11 AMWt590 trayscale[4828]: 2024/09/21 14:38:11 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:16 AMWt590 trayscale[4828]: 2024/09/21 14:38:16 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:21 AMWt590 trayscale[4828]: 2024/09/21 14:38:21 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:26 AMWt590 trayscale[4828]: 2024/09/21 14:38:26 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:31 AMWt590 trayscale[4828]: 2024/09/21 14:38:31 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:36 AMWt590 trayscale[4828]: 2024/09/21 14:38:36 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:41 AMWt590 trayscale[4828]: 2024/09/21 14:38:41 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:46 AMWt590 trayscale[4828]: 2024/09/21 14:38:46 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:47 AMWt590 rtkit-daemon[1417]: Supervising 4 threads of 4 processes of 1 users.
Sep 21 14:38:47 AMWt590 rtkit-daemon[1417]: Supervising 4 threads of 4 processes of 1 users.
Sep 21 14:38:51 AMWt590 trayscale[4828]: 2024/09/21 14:38:51 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:38:56 AMWt590 trayscale[4828]: 2024/09/21 14:38:56 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:01 AMWt590 trayscale[4828]: 2024/09/21 14:39:01 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:06 AMWt590 trayscale[4828]: 2024/09/21 14:39:06 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:11 AMWt590 trayscale[4828]: 2024/09/21 14:39:11 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:16 AMWt590 trayscale[4828]: 2024/09/21 14:39:16 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:18 AMWt590 rtkit-daemon[1417]: Supervising 4 threads of 4 processes of 1 users.
Sep 21 14:39:18 AMWt590 rtkit-daemon[1417]: Supervising 4 threads of 4 processes of 1 users.
Sep 21 14:39:21 AMWt590 trayscale[4828]: 2024/09/21 14:39:21 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:26 AMWt590 trayscale[4828]: 2024/09/21 14:39:26 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:31 AMWt590 trayscale[4828]: 2024/09/21 14:39:31 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:36 AMWt590 trayscale[4828]: 2024/09/21 14:39:36 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:41 AMWt590 trayscale[4828]: 2024/09/21 14:39:41 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:46 AMWt590 trayscale[4828]: 2024/09/21 14:39:46 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:51 AMWt590 trayscale[4828]: 2024/09/21 14:39:51 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:39:56 AMWt590 trayscale[4828]: 2024/09/21 14:39:56 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:01 AMWt590 trayscale[4828]: 2024/09/21 14:40:01 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:06 AMWt590 trayscale[4828]: 2024/09/21 14:40:06 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:11 AMWt590 trayscale[4828]: 2024/09/21 14:40:11 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:16 AMWt590 trayscale[4828]: 2024/09/21 14:40:16 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:21 AMWt590 trayscale[4828]: 2024/09/21 14:40:21 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:26 AMWt590 trayscale[4828]: 2024/09/21 14:40:26 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:31 AMWt590 trayscale[4828]: 2024/09/21 14:40:31 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:36 AMWt590 trayscale[4828]: 2024/09/21 14:40:36 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:41 AMWt590 trayscale[4828]: 2024/09/21 14:40:41 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
Sep 21 14:40:46 AMWt590 trayscale[4828]: 2024/09/21 14:40:46 ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"`

**Comment by jbergler** [comment]
I've just installed 0.14.0 and am also seeing this error in the logs.
Notably, my tailnet does have taildrop enabled. 

@DeedleFake should I report a new issue or would you like to re-open this?

```
ERROR get waiting files err="500 Internal Server Error: Taildrop disabled; no storage directory"
```

**Comment by DeedleFake** [comment]
Very strange. I can't think of what circumstances would show the error when Taildrop is enabled. I took a look through Tailscale's code and that error is only generated in a few places. Maybe something's just weirdly out of sync? Try double-checking your [Taildrop settings](https://tailscale.com/kb/1106/taildrop#enable-taildrop-for-your-network) and then restarting the Tailscale daemon locally.

**Comment by PlexSheep** [comment]
Some additional info:

- Have since switched to GNOME and use a similar application for GTK (I think)
- I'm using a self hosted headscale server, maybe that had something to do with it originally.

**Comment by teto** [comment]
I am running trayscale 0.14.1 and my server has taildrop disabled. I still see a lot of these errors. I dont know if these should be considered errors if the server doesn't support the feature. Maybe a warning ? anyhow I wonder how to silence those ?
