### ISSUE TITLE
change tray icon when exit node is used

### ISSUE THREAD

**Issue by felschr** [DeedleFake/trayscale#99]
Especially with the new Mullvad VPN exit nodes it would be really nice to quickly see if one is connected to an exit node just by looking at the tray icon.

**Comment by jordan-bravo** [comment]
+1 for this feature.

My typical usage looks like this:

- Tailscale is always connected.
- My Mullvad exit node is usually connected.
- Sometimes I need to temporarily disable the Mullvad exit node.

Being able to glance at the tray icon to determine if the Mullvad exit node is connected or not would be extremely useful.

**Comment by DeedleFake** [comment]
This should be a pretty easy change, I think, but I do need to come up with an icon variant. Maybe a little shield in the corner or something?

**Comment by jordan-bravo** [comment]
> This should be a pretty easy change, I think, but I do need to come up with an icon variant. Maybe a little shield in the corner or something?

A shield would work nicely.  

Another option would be the country flag of the connected server.

Another option would be to use a little Mullvad icon, but that would probably run into Trademark issues.  It would have the advantage of being future-compatible if Tailscale ever offers VPN partners beyond Mullvad.

Whatever Trayscale lands on for the tray icon indicator, I think it would be helpful if it were consistent with the icon next to the Mullvad exit node in the main window of the app itself.  Currently the main window of the app shows a yellow circle icon next to the Mullvad exit node.
